### ISSUE TITLE
Possible movement bug?

### ISSUE THREAD

**Issue by CharlieCalv** [wijes/TerminalDesktop#1]
after leaving the desktop it seems that half the time it would make it so walking forward instead makes you walk diagonally left or right.

**Comment by wijes** [comment]
Just using the desktop I can't reproduce this error, are there any specific steps to do this?

**Comment by UmbraMortem13** [comment]
I've had this same issue, it's 100% reproducible for me and only goes away if I use the terminal then leave it without moving the mouse

Steps for 100% reproducible bug
Step 1: Use terminal with this mod installed
Step 2: look to the left or right until the camera stops
Step 3: leave terminal
Step 4: try walking

**Comment by wijes** [comment]
Try the new version 0.5.5, the bug should be fixed

**Comment by UmbraMortem13** [comment]
Issue still persists after update. Upon further inspection, it appears it "locks" the head into facing that direction, causing desync in regards to body and aim direction.

EDIT: So, I had an idea for a quick fix. Please excuse my terminology and assumptions I've made as I am not a unity modder. 

Since using the terminal then immediately leaving seems to fix the issue, as entering the terminal centers the camera/facing direction, couldn't you implement a quick fix of upon leaving the terminal, sending a copy of the center view command that you normally apply on entering the terminal? While obviously not the ideal solution, I feel this could be a good "quick fix" until the source of the issue can be found and solved.

**Comment by wijes** [comment]
Since I still can't reproduce this problem, as a quick solution I tried centralizing the camera when exiting the terminal, but it didn't help.

**Comment by UmbraMortem13** [comment]
After doing some testing and paring down on mods, I found the movement issue stems from LCThirdPerson by xboxcontroller. I tested it with 3rdPerson by Verity and the issue did not persist. For now, LCThirdPerson should probably be marked as incompatible.
